// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Gate.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240713130616_ModelsUpdate")]
    partial class ModelsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Core.Organization.BankRequisites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequisitesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequisitesId");

                    b.ToTable("BankRequisites");
                });

            modelBuilder.Entity("Domain.Core.Organization.Requisites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BIN")
                        .HasColumnType("text");

                    b.Property<int?>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<string>("KBE")
                        .HasColumnType("text");

                    b.Property<string>("LegalAddress")
                        .HasColumnType("text");

                    b.Property<string>("NameEN")
                        .HasColumnType("text");

                    b.Property<string>("NameKZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameRU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("integer");

                    b.Property<string>("PhysicalAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Requisites");
                });

            modelBuilder.Entity("Domain.Core.Sells.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RootCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RootCategoryId");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("Domain.Core.Sells.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("RuleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RuleId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Domain.Core.Sells.PaymentRules.PaymentDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentRuleId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRuleId");

                    b.ToTable("PaymentDates");
                });

            modelBuilder.Entity("Domain.Core.Sells.PaymentRules.PaymentRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("PaymentRules");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Nomenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Nomenclatures");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.StoragedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int?>("StorageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageId");

                    b.ToTable("StoragedProducts");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("RequisitesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("RequisitesId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Domain.Core.Sells.SalableObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<double>("PriceBuy")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceSell")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("SalableObject");

                    b.HasDiscriminator().HasValue("SalableObject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Core.Sells.Service.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Domain.Core.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronomic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Product", b =>
                {
                    b.HasBaseType("Domain.Core.Sells.SalableObject");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("NomenclatureId")
                        .HasColumnType("integer");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NomenclatureId");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Domain.Core.Sells.Service.Service", b =>
                {
                    b.HasBaseType("Domain.Core.Sells.SalableObject");

                    b.Property<int?>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasIndex("CardId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SalableObject", t =>
                        {
                            t.Property("CategoryId")
                                .HasColumnName("Service_CategoryId");
                        });

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("Domain.Core.Organization.BankRequisites", b =>
                {
                    b.HasOne("Domain.Core.Organization.Requisites", null)
                        .WithMany("BankRequisites")
                        .HasForeignKey("RequisitesId");
                });

            modelBuilder.Entity("Domain.Core.Organization.Requisites", b =>
                {
                    b.HasOne("Domain.Core.Users.User", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Domain.Core.Sells.Category", b =>
                {
                    b.HasOne("Domain.Core.Sells.Category", "RootCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("RootCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RootCategory");
                });

            modelBuilder.Entity("Domain.Core.Sells.Payment", b =>
                {
                    b.HasOne("Domain.Core.Users.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Core.Users.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Core.Sells.PaymentRules.PaymentRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Provider");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Domain.Core.Sells.PaymentRules.PaymentDate", b =>
                {
                    b.HasOne("Domain.Core.Sells.PaymentRules.PaymentRule", null)
                        .WithMany("Dates")
                        .HasForeignKey("PaymentRuleId");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.StoragedProduct", b =>
                {
                    b.HasOne("Domain.Core.Sells.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Core.Sells.Products.Storage", null)
                        .WithMany("Products")
                        .HasForeignKey("StorageId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Supplier", b =>
                {
                    b.HasOne("Domain.Core.Sells.Products.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Core.Organization.Requisites", "Requisites")
                        .WithMany()
                        .HasForeignKey("RequisitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Requisites");
                });

            modelBuilder.Entity("Domain.Core.Sells.SalableObject", b =>
                {
                    b.HasOne("Domain.Core.Sells.Payment", null)
                        .WithMany("Cart")
                        .HasForeignKey("PaymentId");
                });

            modelBuilder.Entity("Domain.Core.Sells.Service.Card", b =>
                {
                    b.HasOne("Domain.Core.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Core.Users.User", b =>
                {
                    b.HasOne("Domain.Core.Sells.Service.Service", null)
                        .WithMany("Providers")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Product", b =>
                {
                    b.HasOne("Domain.Core.Sells.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Core.Sells.Products.Nomenclature", null)
                        .WithMany("Products")
                        .HasForeignKey("NomenclatureId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Core.Sells.Service.Service", b =>
                {
                    b.HasOne("Domain.Core.Sells.Service.Card", null)
                        .WithMany("ConnectedServices")
                        .HasForeignKey("CardId");

                    b.HasOne("Domain.Core.Sells.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Core.Organization.Requisites", b =>
                {
                    b.Navigation("BankRequisites");
                });

            modelBuilder.Entity("Domain.Core.Sells.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("Domain.Core.Sells.Payment", b =>
                {
                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Domain.Core.Sells.PaymentRules.PaymentRule", b =>
                {
                    b.Navigation("Dates");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Nomenclature", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Core.Sells.Products.Storage", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Core.Sells.Service.Card", b =>
                {
                    b.Navigation("ConnectedServices");
                });

            modelBuilder.Entity("Domain.Core.Sells.Service.Service", b =>
                {
                    b.Navigation("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
